-- MySQL Script generated by MySQL Workbench
-- Tue Jun 24 19:56:07 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema library
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema library
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `library` DEFAULT CHARACTER SET utf8 ;
USE `library` ;

-- -----------------------------------------------------
-- Table `library`.`PAIS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `library`.`PAIS` ;

CREATE TABLE IF NOT EXISTS `library`.`PAIS` (
  `idPAIS` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `codigo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPAIS`),
  UNIQUE INDEX `idtable1_UNIQUE` (`idPAIS` ASC) VISIBLE,
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE,
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`EDITORIAL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `library`.`EDITORIAL` ;

CREATE TABLE IF NOT EXISTS `library`.`EDITORIAL` (
  `idEDITORIAL` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `PAIS_idPAIS` INT NOT NULL,
  PRIMARY KEY (`idEDITORIAL`),
  UNIQUE INDEX `idEDITORIAL_UNIQUE` (`idEDITORIAL` ASC) VISIBLE,
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE,
  INDEX `fk_EDITORIAL_PAIS1_idx` (`PAIS_idPAIS` ASC) VISIBLE,
  CONSTRAINT `fk_EDITORIAL_PAIS1`
    FOREIGN KEY (`PAIS_idPAIS`)
    REFERENCES `library`.`PAIS` (`idPAIS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`GENERO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `library`.`GENERO` ;

CREATE TABLE IF NOT EXISTS `library`.`GENERO` (
  `idGENERO` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idGENERO`),
  UNIQUE INDEX `idGENERO_UNIQUE` (`idGENERO` ASC) VISIBLE,
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`LIBRO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `library`.`LIBRO` ;

CREATE TABLE IF NOT EXISTS `library`.`LIBRO` (
  `idLIBRO` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `isbn` VARCHAR(45) NOT NULL,
  `anio_publicacion` INT NULL DEFAULT 0,
  `sinopsis` VARCHAR(45) NULL,
  `EDITORIAL_idEDITORIAL` INT NOT NULL,
  `GENERO_idGENERO` INT NOT NULL,
  PRIMARY KEY (`idLIBRO`),
  UNIQUE INDEX `idLIBRO_UNIQUE` (`idLIBRO` ASC) VISIBLE,
  INDEX `fk_LIBRO_EDITORIAL_idx` (`EDITORIAL_idEDITORIAL` ASC) VISIBLE,
  INDEX `fk_LIBRO_GENERO1_idx` (`GENERO_idGENERO` ASC) VISIBLE,
  CONSTRAINT `fk_LIBRO_EDITORIAL`
    FOREIGN KEY (`EDITORIAL_idEDITORIAL`)
    REFERENCES `library`.`EDITORIAL` (`idEDITORIAL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LIBRO_GENERO1`
    FOREIGN KEY (`GENERO_idGENERO`)
    REFERENCES `library`.`GENERO` (`idGENERO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`AUTOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `library`.`AUTOR` ;

CREATE TABLE IF NOT EXISTS `library`.`AUTOR` (
  `idAUTOR` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `fecha_nacimiento` DATE NULL,
  `PAIS_idPAIS` INT NOT NULL,
  PRIMARY KEY (`idAUTOR`),
  UNIQUE INDEX `idAUTOR_UNIQUE` (`idAUTOR` ASC) VISIBLE,
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE,
  INDEX `fk_AUTOR_PAIS1_idx` (`PAIS_idPAIS` ASC) VISIBLE,
  CONSTRAINT `fk_AUTOR_PAIS1`
    FOREIGN KEY (`PAIS_idPAIS`)
    REFERENCES `library`.`PAIS` (`idPAIS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `library`.`LIBROAUTOR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `library`.`LIBROAUTOR` ;

CREATE TABLE IF NOT EXISTS `library`.`LIBROAUTOR` (
  `AUTOR_idAUTOR` INT NOT NULL,
  `LIBRO_idLIBRO` INT NOT NULL,
  INDEX `fk_LIBROAUTOR_AUTOR1_idx` (`AUTOR_idAUTOR` ASC) VISIBLE,
  INDEX `fk_LIBROAUTOR_LIBRO1_idx` (`LIBRO_idLIBRO` ASC) VISIBLE,
  CONSTRAINT `fk_LIBROAUTOR_AUTOR1`
    FOREIGN KEY (`AUTOR_idAUTOR`)
    REFERENCES `library`.`AUTOR` (`idAUTOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LIBROAUTOR_LIBRO1`
    FOREIGN KEY (`LIBRO_idLIBRO`)
    REFERENCES `library`.`LIBRO` (`idLIBRO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
